using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DB_Generator
{
    class Countries
    {
        public static List<Country> countries = new List<Country>
        {
 new Country(1,"Brazil"),
new Country(2,"Slovenia"),
new Country(3,"Greece"),
new Country(4,"Ireland"),
new Country(5,"Colombia"),
new Country(6,"Russian Federation"),
new Country(7,"Argentina"),
new Country(8,"Ecuador"),
new Country(9,"Mexico"),
new Country(10,"Libya"),
new Country(11,"France"),
new Country(12,"Algeria"),
new Country(13,"United Arab Emirates"),
new Country(14,"Kazakhstan"),
new Country(15,"France"),
new Country(16,"Latvia"),
new Country(17,"Germany"),
new Country(18,"Botswana"),
new Country(19,"New Caledonia"),
new Country(20,"Canada"),
new Country(21,"China (People's Republic of)"),
new Country(22,"France"),
new Country(23,"Spain"),
new Country(24,"France"),
new Country(25,"India"),
new Country(26,"Korea, Democratic People's Republic of"),
new Country(27,"Macao SAR, China"),
new Country(28,"Madagascar"),
new Country(29,"Malta"),
new Country(30,"Mauritius"),
new Country(31,"Moldova, Republic of"),
new Country(32,"Namibia"),
new Country(33,"New Zealand"),
new Country(34,"Independent State of Papua New Guinea"),
new Country(35,"Spain"),
new Country(36,"Italy"),
new Country(37,"Serbia"),
new Country(38,"Seychelles"),
new Country(39,"French Polynesia"),
new Country(40,"French Polynesia"),
new Country(41,"Canada"),
new Country(42,"Uganda"),
new Country(43,"Vanuatu"),
new Country(44,"Russian Federation"),
new Country(45,"New Caledonia"),
new Country(46,"South Africa"),
new Country(47,"United States"),
new Country(48,"Italy"),
new Country(49,"Japan"),
new Country(50,"Egypt"),
new Country(51,"Kenya"),
new Country(52,"United States"),
new Country(53,"Nigeria"),
new Country(54,"Israel"),
new Country(55,"United States"),
new Country(56,"Korea"),
new Country(57,"United States"),
new Country(58,"Turkey"),
new Country(59,"Argentina"),
new Country(60,"Austria"),
new Country(61,"Colombia"),
new Country(62,"Brazil"),
new Country(63,"Azerbaijan"),
new Country(64,"Bosnia and Herzegovina"),
new Country(65,"Thailand"),
new Country(66,"Belarus"),
new Country(67,"Bulgaria"),
new Country(68,"Bangladesh"),
new Country(69,"Spain"),
new Country(70,"Italy"),
new Country(71,"Finland"),
new Country(72,"United Kingdom"),
new Country(73,"Bolivia"),
new Country(74,"United Kingdom"),
new Country(75,"Belgium"),
new Country(76,"Bulgaria"),
new Country(77,"Israel"),
new Country(78,"Canada"),
new Country(79,"Luxembourg"),
new Country(80,"Jamaica"),
new Country(81,"Romania"),
new Country(82,"Hong Kong SAR, China"),
new Country(83,"Chinese Taipei"),
new Country(84,"China (People's Republic of)"),
new Country(85,"China (People's Republic of)"),
new Country(86,"China (People's Republic of)"),
new Country(87,"China (People's Republic of)"),
new Country(88,"Ireland"),
new Country(89,"South Africa"),
new Country(90,"Germany"),
new Country(91,"Panama"),
new Country(92,"Turkey"),
new Country(93,"France"),
new Country(94,"Croatia"),
new Country(95,"Cuba"),
new Country(96,"Cyprus"),
new Country(97,"Czech Republic"),
new Country(98,"United States"),
new Country(99,"United Kingdom"),
new Country(100,"Bahrain"),
new Country(101,"Russian Federation"),
new Country(102,"Hong Kong SAR, China"),
new Country(103,"Egypt"),
new Country(104,"Israel"),
new Country(105,"United Arab Emirates"),
new Country(106,"Estonia"),
new Country(107,"Ethiopia"),
new Country(108,"United Arab Emirates"),
new Country(109,"Portugal"),
new Country(110,"Germany"),
new Country(111,"Germany"),
new Country(112,"Chinese Taipei"),
new Country(113,"United States"),
new Country(114,"Fiji"),
new Country(115,"Finland"),
new Country(116,"United Kingdom"),
new Country(117,"Turkey"),
new Country(118,"Indonesia"),
new Country(119,"Georgia"),
new Country(120,"Germany"),
new Country(121,"Bahrain"),
new Country(122,"Germany"),
new Country(123,"China (People's Republic of)"),
new Country(124,"United States"),
new Country(125,"Portugal"),
new Country(126,"Hong Kong SAR, China"),
new Country(127,"Hong Kong SAR, China"),
new Country(128,"Spain"),
new Country(129,"Iceland"),
new Country(130,"Curaçao"),
new Country(131,"South Africa"),
new Country(132,"Austria"),
new Country(133,"Iran, Islamic Republic of"),
new Country(134,"Iran, Islamic Republic of"),
new Country(135,"Israel"),
new Country(136,"Japan"),
new Country(137,"Kuwait"),
new Country(138,"India"),
new Country(139,"India"),
new Country(140,"United States"),
new Country(141,"Jordan"),
new Country(142,"Russian Federation"),
new Country(143,"Russian Federation"),
new Country(144,"China (People's Republic of)"),
new Country(145,"Kenya"),
new Country(146,"Iran, Islamic Republic of"),
new Country(147,"Netherlands"),
new Country(148,"Korea"),
new Country(149,"Kuwait"),
new Country(150,"Costa Rica"),
new Country(151,"Mozambique"),
new Country(152,"Chile"),
new Country(153,"Argentina"),
new Country(154,"Chile"),
new Country(155,"Peru"),
new Country(156,"Ecuador"),
new Country(157,"Antigua and Barbuda"),
new Country(158,"Libya"),
new Country(159,"Russian Federation"),
new Country(160,"Poland"),
new Country(161,"Germany"),
new Country(162,"Germany"),
new Country(163,"Germany"),
new Country(164,"Luxembourg"),
new Country(165,"Iran, Islamic Republic of"),
new Country(166,"Malaysia"),
new Country(167,"Sweden"),
new Country(168,"Netherlands"),
new Country(169,"Mexico"),
new Country(170,"Lebanon"),
new Country(171,"Italy"),
new Country(172,"Mongolia"),
new Country(173,"Montenegro"),
new Country(174,"Egypt"),
new Country(175,"Austria"),
new Country(176,"Egypt"),
new Country(177,"Japan"),
new Country(178,"Tunisia"),
new Country(179,"Greece"),
new Country(180,"Oman"),
new Country(181,"Turkey"),
new Country(182,"Philippines"),
new Country(183,"Turkey"),
new Country(184,"Portugal"),
new Country(185,"Pakistan"),
new Country(186,"Tanzania, United Republic of"),
new Country(187,"Switzerland"),
new Country(188,"Australia"),
new Country(189,"Qatar"),
new Country(190,"Russian Federation"),
new Country(191,"Morocco"),
new Country(192,"Brunei Darussalam"),
new Country(193,"Jordan"),
new Country(194,"South Africa"),
new Country(195,"South Africa"),
new Country(196,"Afghanistan"),
new Country(197,"Sweden"),
new Country(198,"Portugal"),
new Country(199,"Portugal"),
new Country(200,"Saudi Arabia"),
new Country(201,"China (People's Republic of)"),
new Country(202,"China (People's Republic of)"),
new Country(203,"China (People's Republic of)"),
new Country(204,"Singapore"),
new Country(205,"Singapore"),
new Country(206,"Russian Federation"),
new Country(207,"China (People's Republic of)"),
new Country(208,"Singapore"),
new Country(209,"South Africa"),
new Country(210,"Sri Lanka"),
new Country(211,"Sudan"),
new Country(212,"Turkey"),
new Country(213,"Suriname"),
new Country(214,"Switzerland"),
new Country(215,"Tunisia"),
new Country(216,"Syrian Arab Republic"),
new Country(217,"Angola"),
new Country(218,"El Salvador"),
new Country(219,"Peru"),
new Country(220,"Cape Verde"),
new Country(221,"Paraguay"),
new Country(222,"Brazil"),
new Country(223,"Ecuador"),
new Country(224,"Portugal"),
new Country(225,"Romania"),
new Country(226,"Algeria"),
new Country(227,"Thailand"),
new Country(228,"Turkey"),
new Country(229,"China (People's Republic of)"),
new Country(230,"Belgium"),
new Country(231,"Russian Federation"),
new Country(232,"Chinese Taipei"),
new Country(233,"Germany"),
new Country(234,"Tunisia"),
new Country(235,"Ukraine"),
new Country(236,"United States"),
new Country(237,"United States"),
new Country(238,"United States"),
new Country(239,"Russian Federation"),
new Country(240,"Uzbekistan"),
new Country(241,"Vietnam"),
new Country(242,"United Kingdom"),
new Country(243,"Australia"),
new Country(244,"Belgium"),
new Country(245,"Mexico"),
new Country(246,"Russian Federation"),
new Country(247,"Brazil"),
new Country(248,"Portugal"),
new Country(249,"Norway"),
new Country(250,"China (People's Republic of)"),
new Country(251,"Yemen"),
new Country(252,"Azerbaijan"),
new Country(253,"Azerbaijan")
        };
    }
}
